const express = require('express')
const router = express.Router()
const User = require('../controllers/userController')
const authenLogin = require('../helpers/middleware')

router.get('/', authenLogin, User.showAll)
router.get('/register',User.register)
router.post('/register',User.create)
router.get('/delete/:id', authenLogin, User.delete)
router.get('/edit/:id', authenLogin, User.edit)
router.post('/edit/:id', authenLogin, User.update)
router.get('/:id/buy', authenLogin, User.buyDrug)
router.post('/:id/buy', authenLogin, User.createTransaction)
router.get('/:id/buy/invoice', authenLogin, User.invoice)
module.exports = router